/*
 * generated by Xtext 2.44.0
 */
package ntnu.tdt4250.cardgames.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CardgamesDSLStandaloneSetup extends CardgamesDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new CardgamesDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
