/*
 * generated by Xtext 2.44.0
 */
package ntnu.tdt4250.cardgames.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class CardgamesDSLIdeModule extends AbstractCardgamesDSLIdeModule {
}
