/*
 * generated by Xtext 2.44.0
 */
package ntnu.tdt4250.cardgames.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import ntnu.tdt4250.cardgames.dsl.CardgamesDSLRuntimeModule;
import ntnu.tdt4250.cardgames.dsl.CardgamesDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CardgamesDSLIdeSetup extends CardgamesDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CardgamesDSLRuntimeModule(), new CardgamesDSLIdeModule()));
	}
	
}
