/*
 * generated by Xtext 2.44.0
 */
package ntnu.tdt4250.cardgames.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CardgamesDSLUiModule extends AbstractCardgamesDSLUiModule {

	public CardgamesDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
