/*
 * generated by Xtext 2.44.0
 */
package ntnu.tdt4250.cardgames.dsl.formatting2

import com.google.inject.Inject
import ntnu.tdt4250.cardgame.CardGame
import ntnu.tdt4250.cardgame.Deck
import ntnu.tdt4250.cardgames.dsl.services.CardgamesDSLGrammarAccess
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument

class CardgamesDSLFormatter extends AbstractFormatter2 {
	
	@Inject extension CardgamesDSLGrammarAccess

	def dispatch void format(CardGame cardGame, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		cardGame.deck.format
		for (rule : cardGame.rules) {
			rule.format
		}
		for (role : cardGame.roles) {
			role.format
		}
		for (cardExchange : cardGame.exchanges) {
			cardExchange.format
		}
		cardGame.winCondition.format
		cardGame.hand.format
	}

	def dispatch void format(Deck deck, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (suit : deck.suits) {
			suit.format
		}
		for (rank : deck.ranks) {
			rank.format
		}
	}
	
}
