/*
 * generated by Xtext 2.44.0
 */
package ntnu.tdt4250.cardgames.dsl.tests

import com.google.inject.Inject
import ntnu.tdt4250.cardgame.CardGame
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(CardgamesDSLInjectorProvider)
class CardgamesDSLParsingTest {
	@Inject
	ParseHelper<CardGame> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
