<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cardgame" nsURI="http://tdt4250.ntnu.no/cardgames" nsPrefix="cardgames">
  <eClassifiers xsi:type="ecore:EClass" name="Suit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="card" lowerBound="1" eType="#//Card"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rank">
    <eStructuralFeatures xsi:type="ecore:EReference" name="card" lowerBound="1" eType="#//Card"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Card">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deck" lowerBound="1" upperBound="52"
        eType="#//Deck"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hand" upperBound="52" eType="#//Hand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pile" upperBound="52" eType="#//Pile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="card" upperBound="-1" eType="#//Card"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecialCardRule" eSuperTypes="#//Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClearPileRule" eSuperTypes="#//Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deck"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pile"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hand" eType="#//Hand"/>
  </eClassifiers>
</ecore:EPackage>
    