#

pluginName = ntnu.tdt4250.cardgames Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Suit_type = Suit
_UI_Rank_type = Rank
_UI_Card_type = Card
_UI_Rule_type = Rule
_UI_SpecialCardRule_type = Special Card Rule
_UI_ClearPileRule_type = Clear Pile Rule
_UI_Deck_type = Deck
_UI_Pile_type = Pile
_UI_Hand_type = Hand
_UI_Role_type = Role
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Suit_card_feature = Card
_UI_Rank_card_feature = Card
_UI_Card_deck_feature = Deck
_UI_Card_hand_feature = Hand
_UI_Card_pile_feature = Pile
_UI_Rule_card_feature = Card
_UI_Role_hand_feature = Hand
_UI_Unknown_feature = Unspecified

_UI_CardGame_type = Card Game
_UI_CardExchange_type = Card Exchange
_UI_WinCondition_type = Win Condition
_UI_PlayRule_type = Play Rule
_UI_firstEmptyHand_type = first Empty Hand
_UI_Suit_name_feature = Name
_UI_Rank_name_feature = Name
_UI_Rank_value_feature = Value
_UI_SpecialCardRule_rank_feature = Rank
_UI_SpecialCardRule_suit_feature = Suit
_UI_SpecialCardRule_alwaysPlayable_feature = Always Playable
_UI_SpecialCardRule_effect_feature = Effect
_UI_ClearPileRule_numberOfSameRequiredToClear_feature = Number Of Same Required To Clear
_UI_ClearPileRule_playerWhoClearedStarts_feature = Player Who Cleared Starts
_UI_Deck_suits_feature = Suits
_UI_Deck_ranks_feature = Ranks
_UI_Hand_allCards_feature = All Cards
_UI_Hand_fixedPerPlayer_feature = Fixed Per Player
_UI_Role_name_feature = Name
_UI_Role_order_feature = Order
_UI_CardGame_deck_feature = Deck
_UI_CardGame_rules_feature = Rules
_UI_CardGame_roles_feature = Roles
_UI_CardGame_exchanges_feature = Exchanges
_UI_CardGame_winCondition_feature = Win Condition
_UI_CardGame_hand_feature = Hand
_UI_CardGame_minPlayers_feature = Min Players
_UI_CardGame_maxPlayers_feature = Max Players
_UI_CardExchange_to_feature = To
_UI_CardExchange_from_feature = From
_UI_CardExchange_numberOfCards_feature = Number Of Cards
_UI_PlayRule_minimumNumberOfCards_feature = Minimum Number Of Cards
_UI_PlayRule_maximumNumberOfCards_feature = Maximum Number Of Cards
_UI_PlayRule_requireSameAmountOfCards_feature = Require Same Amount Of Cards
_UI_PlayRule_requireSameRank_feature = Require Same Rank
_UI_PlayRule_validPlayTypes_feature = Valid Play Types
_UI_firstEmptyHand_continueToOneLeft_feature = Continue To One Left
_UI_ValidPlayType_SAME_RANK_literal = SAME_RANK
_UI_ValidPlayType_SAME_SUIT_literal = SAME_SUIT
_UI_ValidPlayType_HIGHER_RANK_literal = HIGHER_RANK
_UI_ValidPlayType_LOWER_RANK_literal = LOWER_RANK
_UI_Effect_CLEAR_PILE_literal = CLEAR_PILE
_UI_Effect_CHANGE_VALID_SUIT_literal = CHANGE_VALID_SUIT
