/*
 * generated by Xtext 2.44.0
 */
package ntnu.tdt4250.cardgames.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CardgamesDSLRuntimeModule extends AbstractCardgamesDSLRuntimeModule {
}
